### ISSUE TITLE
undeclared name: AnonymousMessage1 and AnonymousMessage2

### ISSUE THREAD

**Issue by tigerinus** [asyncapi/go-watermill-template#168]
#### Describe the bug

There are undeclared vars in the generated code.

#### How to Reproduce

1. Create a new go module at `./whatever` folder
2. Create AsyncAPI file at `/tmp/amqp.yaml` with following content (got this example yaml from `@async/cli`)

```yaml
asyncapi: 2.4.0
id: 'urn:rpc:example:server'
defaultContentType: application/json
info:
  title: RPC Server Example
  description: This example demonstrates how to define an RPC server.
  version: 1.0.0
servers:
  production:
    url: rabbitmq.example.org
    protocol: amqp
channels:
  '{queue}':
    parameters:
      queue:
        schema:
          type: string
          pattern: ^amq\\.gen\\-.+$
    bindings:
      amqp:
        is: queue
        queue:
          exclusive: true
    subscribe:
      operationId: sendSumResult
      bindings:
        amqp:
          ack: true
      message:
        correlationId:
          location: $message.header#/correlation_id
        payload:
          type: object
          properties:
            result:
              type: number
              examples:
                - 7
  rpc_queue:
    bindings:
      amqp:
        is: queue
        queue:
          durable: false
    publish:
      operationId: sum
      message:
        bindings:
          amqp:
            replyTo:
              type: string
        correlationId:
          location: $message.header#/correlation_id
        payload:
          type: object
          properties:
            numbers:
              type: array
              items:
                type: number
              examples:
                - - 4
                  - 3
```

3. Run `ag /tmp/amqp.yaml @asyncapi/go-watermill-template -o . -p moduleName=whatever` in the module folder `./whatever`

4. Run `go build`

```bash
$ go build
# whatever/asyncapi
asyncapi/handlers.go:18:12: undefined: AnonymousMessage2
asyncapi/handlers.go:28:68: undefined: AnonymousMessage1
```

#### Expected behavior

The build completes successfully.

**Comment by dxps** [comment]
There are two problems here, both easily solvable:
1. The (Go) structs for the messages (generated in `payloads.go` file) gets some "untitled" `AnonymousSchema...` names.
2. The reference to these structs (generated in `handlers.go` and `main.go`) gets some `AnonymousMessage...` names.

To solve these, you have to "enhance" a bit your spec by specifying
1. `$id` in the message payload. This becomes the name of the generated Go struct.
2. `messageId` in the {channel-name} > {operation-name: publish / subscribe} > message.

See your spec (`amqp.yml` file), updated accordingly with the aforementioned details:
```yaml
asyncapi: 2.4.0
id: "urn:rpc:example:server"
defaultContentType: application/json
info:
  title: RPC Server Example
  description: This example demonstrates how to define an RPC server.
  version: 1.0.0

servers:
  production:
    url: rabbitmq.example.org
    protocol: amqp

channels:
  "{queue}":
    parameters:
      queue:
        schema:
          type: string
          pattern: ^amq\\.gen\\-.+$
    bindings:
      amqp:
        is: queue
        queue:
          exclusive: true
    subscribe:
      operationId: sendSumResult
      bindings:
        amqp:
          ack: true
      message:
        messageId: SumOutput
        correlationId:
          location: $message.header#/correlation_id
        payload:
          $id: SumOutput
          type: object
          properties:
            result:
              type: number
              examples:
                - 7

  rpc_queue:
    bindings:
      amqp:
        is: queue
        queue:
          durable: false
    publish:
      operationId: sum
      message:
        messageId: SumInput
        bindings:
          amqp:
            replyTo:
              type: string
        correlationId:
          location: $message.header#/correlation_id
        payload:
          $id: SumInput
          type: object
          properties:
            numbers:
              type: array
              items:
                type: number
              examples:
                - - 4
                  - 3
```

Tested using `ag amqp.yaml @asyncapi/go-watermill-template -p moduleName=whatever -o ./gencode`
And it's all looking good now: `cd gencode && go build` is silent (no more errors). :blush:

In the following days I'll submit a PR to update the docs.
