### ISSUE TITLE
Failure to generate AMQP channel bindings without queue definition

### ISSUE THREAD

**Issue by tommitytom** [asyncapi/go-watermill-template#180]
#### Describe the bug
In the AMQP documentation, it states that an AMQP binding can be set up for a channel as either a `routingKey` (exchange) or a `queue`, set via the `is` key. https://github.com/asyncapi/bindings/blob/master/amqp/README.md#channel-binding-object

This would lead me to believe that a channel binding can only be one or the other.  I'm trying to set up a channel that interacts with a RabbitMQ exchange, so I am leaving out the `queue` definition as I presume it is not needed, however this causes the following crash: 

```
Something went wrong:
TypeError: Cannot read properties of undefined (reading 'name')
    at map (C:\Users\Tom\AppData\Roaming\npm\node_modules\@asyncapi\generator\node_modules\@asyncapi\go-watermill-template\components\Router.js:18:23)
    at Array.map (<anonymous>)
    at AMQPRouterRules (C:\Users\Tom\AppData\Roaming\npm\node_modules\@asyncapi\generator\node_modules\@asyncapi\go-watermill-template\components\Router.js:15:6)
    at createElement (C:\Users\Tom\AppData\Roaming\npm\node_modules\@asyncapi\generator\node_modules\@asyncapi\generator-react-sdk\src\renderer\renderer.ts:46:26)
    at Object.render (C:\Users\Tom\AppData\Roaming\npm\node_modules\@asyncapi\generator\node_modules\@asyncapi\generator-react-sdk\src\renderer\renderer.ts:74:16)
```

#### How to Reproduce

Create a channel with an AMQP binding without a queue definition, like the following:

```
channels:
  user/signedup:
    bindings:
      amqp:
        is: routingKey
        exchange:
          name: myExchange
          type: topic
          durable: true
          autoDelete: false
          vhost: /
        bindingVersion: 0.2.0
```

#### Expected behavior

I expected the code to be generated without error.  The definition works fine with the HTML documentation generator.
